const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors());

// VTT টাইম (00:01:23.456) কে সেকেন্ডে কনভার্ট করার ফাংশন
function parseTime(timeStr) {
    const parts = timeStr.trim().split(':');
    let sec = 0;
    if (parts.length === 3) {
        sec = parseInt(parts[0]) * 3600 + parseInt(parts[1]) * 60 + parseFloat(parts[2]);
    } else if (parts.length === 2) {
        sec = parseInt(parts[0]) * 60 + parseFloat(parts[1]);
    }
    return sec;
}

app.get('/transcript', async (req, res) => {
    const videoId = req.query.videoId;
    if (!videoId) return res.status(400).json({ error: 'videoId is required' });

    // ৬টি হাই-স্পিড ওপেন-সোর্স API সার্ভারের লিস্ট
    const apiInstances = [
        'https://api.piped.privacydev.net',
        'https://pipedapi.tokhmi.xyz',
        'https://pipedapi.smnz.de',
        'https://piped-api.lunar.icu',
        'https://pipedapi.syncpundit.io',
        'https://pipedapi.kavin.rocks'
    ];

    let lastError = "All API instances failed.";

    // একটি ফেইল করলে স্বয়ংক্রিয়ভাবে পরেরটিতে যাওয়ার লুপ
    for (const instance of apiInstances) {
        try {
            console.log(`Trying to fetch from: ${instance}`);
            
            const response = await fetch(`${instance}/streams/${videoId}`, {
                headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' }
            });

            // Cloudflare এর HTML ব্লক (Unexpected token <) এড়ানোর জন্য চেক করা হচ্ছে
            const contentType = response.headers.get("content-type");
            if (!response.ok || !contentType || !contentType.includes("application/json")) {
                throw new Error(`Server returned HTML or Blocked. Skipping...`);
            }
            
            const data = await response.json();
            
            if (!data.subtitles || data.subtitles.length === 0) {
                throw new Error("No subtitles found in this API.");
            }

            // ইংরেজি সাবটাইটেল (ম্যানুয়াল বা অটো-জেনারেটেড) খোঁজা
            let targetSub = data.subtitles.find(s => s.name.toLowerCase().includes('english') && !s.autoGenerated);
            if (!targetSub) targetSub = data.subtitles.find(s => s.name.toLowerCase().includes('english'));
            if (!targetSub) targetSub = data.subtitles[0];

            // সাবটাইটেল ফাইল ডাউনলোড
            const subResponse = await fetch(targetSub.url);
            if (!subResponse.ok) throw new Error("Failed to download VTT file");
            
            const vttText = await subResponse.text();
            
            // সাবটাইটেল পার্স করা
            const transcript = [];
            const blocks = vttText.split(/\n\s*\n/); 
            
            for (const block of blocks) {
                const lines = block.split('\n').map(l => l.trim());
                const timeLineIdx = lines.findIndex(l => l.includes('-->'));
                
                if (timeLineIdx !== -1) {
                    const [startStr, endStr] = lines[timeLineIdx].split(/\s+-->\s+/);
                    const textLines = lines.slice(timeLineIdx + 1).filter(l => l && !l.startsWith('<v'));
                    let text = textLines.join(' ').replace(/<[^>]+>/g, '').replace(/\[.*?\]/g, '').trim(); 
                    text = text.replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"');

                    if (text && text.length > 0) {
                        transcript.push({
                            start: parseTime(startStr),
                            end: parseTime(endStr),
                            en: text
                        });
                    }
                }
            }

            // যদি সফলভাবে সাবটাইটেল পেয়ে যায়, তবে ফ্রন্টএন্ডে পাঠিয়ে লুপ ব্রেক করবে
            if (transcript.length > 0) {
                console.log(`Success! Subtitles fetched from ${instance}`);
                return res.json(transcript); 
            } else {
                throw new Error("Parsed transcript is empty.");
            }

        } catch (err) {
            console.log(`Failed on ${instance}: ${err.message}`);
            lastError = err.message;
            // ফেইল করলে লুপ ঘুরে ২য় সার্ভারে চলে যাবে
        }
    }

    // ৬টি সার্ভারই ফেইল করলে এই মেসেজটি দেখাবে
    res.status(500).json({ error: `Subtitles blocked by YouTube. Last Error: ${lastError}` });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Smart Server running on port ${PORT}`);
});
