const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors());

// WebVTT এর টাইমস্ট্যাম্প (00:01:23.456) কে সেকেন্ডে কনভার্ট করার ফাংশন
function parseTime(timeStr) {
    const parts = timeStr.trim().split(':');
    let sec = 0;
    if (parts.length === 3) {
        sec = parseInt(parts[0]) * 3600 + parseInt(parts[1]) * 60 + parseFloat(parts[2]);
    } else if (parts.length === 2) {
        sec = parseInt(parts[0]) * 60 + parseFloat(parts[1]);
    }
    return sec;
}

app.get('/transcript', async (req, res) => {
    const videoId = req.query.videoId;
    if (!videoId) return res.status(400).json({ error: 'videoId is required' });

    // ৩টি আলাদা গ্লোবাল ওপেন-সোর্স API সার্ভার (IP Block এড়াতে)
    const apiInstances = [
        'https://pipedapi.kavin.rocks',
        'https://api.piped.projectsegfau.lt',
        'https://pipedapi.tokhmi.xyz'
    ];

    let lastError = "Failed to fetch from all API sources";

    for (const instance of apiInstances) {
        try {
            console.log(`Trying fetch from: ${instance}`);
            
            // API থেকে ভিডিওর ডাটা আনা
            const response = await fetch(`${instance}/streams/${videoId}`);
            if (!response.ok) throw new Error(`API Responded with HTTP ${response.status}`);
            
            const data = await response.json();
            
            if (!data.subtitles || data.subtitles.length === 0) {
                throw new Error("No subtitles found for this video.");
            }

            // ইংরেজি সাবটাইটেল ফিল্টার করা (ম্যানুয়ালকে আগে প্রাধান্য দেওয়া হবে)
            let targetSub = data.subtitles.find(s => s.name.toLowerCase().includes('english') && !s.autoGenerated);
            if (!targetSub) targetSub = data.subtitles.find(s => s.name.toLowerCase().includes('english'));
            if (!targetSub) targetSub = data.subtitles[0];

            // সাবটাইটেল (VTT) ফাইলটি ডাউনলোড করা
            const subResponse = await fetch(targetSub.url);
            if (!subResponse.ok) throw new Error("Failed to download subtitle file");
            
            const vttText = await subResponse.text();
            
            // WebVTT ফাইলকে JSON-এ কনভার্ট করা
            const transcript = [];
            const blocks = vttText.split(/\n\s*\n/); // ডাবল এন্টার দিয়ে ব্লক আলাদা করা
            
            for (const block of blocks) {
                const lines = block.split('\n').map(l => l.trim());
                // যে লাইনে '-->' আছে, সেটি হলো সময়ের লাইন
                const timeLineIdx = lines.findIndex(l => l.includes('-->'));
                
                if (timeLineIdx !== -1) {
                    const [startStr, endStr] = lines[timeLineIdx].split(/\s+-->\s+/);
                    
                    // টেক্সট লাইনগুলো বের করে আনা এবং অপ্রয়োজনীয় HTML/VTT ট্যাগ মুছে ফেলা
                    const textLines = lines.slice(timeLineIdx + 1).filter(l => l && !l.startsWith('<v'));
                    let text = textLines.join(' ').replace(/<[^>]+>/g, '').replace(/\[.*?\]/g, '').trim(); 
                    
                    text = text.replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"');

                    if (text && text.length > 0) {
                        transcript.push({
                            start: parseTime(startStr),
                            end: parseTime(endStr),
                            en: text
                        });
                    }
                }
            }

            if (transcript.length > 0) {
                return res.json(transcript); // সফল হলে ডেটা পাঠিয়ে লুপ বন্ধ করা
            } else {
                throw new Error("Transcript file is empty or unreadable");
            }

        } catch (err) {
            console.error(`Error on ${instance}:`, err.message);
            lastError = err.message;
            // ফেইল করলে লুপ ঘুরে পরের instance এ চেষ্টা করবে
        }
    }

    // ৩টি সার্ভারই ফেইল করলে এরর দেখানো
    res.status(500).json({ error: `Blocked or No Subtitles available. Details: ${lastError}` });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
